#!/usr/bin/env bash

set -eax

PROJECT=${PROJECT:-$(basename ${PWD} | sed s/[\w.-]//g)}

if [ -d "persistence" ]
    then
    read -p "Are you sure? " -n 1 -r
    if [[ $REPLY =~ ^[Yy]$ ]]
        then
	docker-compose -p $(PROJECT) -f $(DOCKER_COMPOSE_FILE) down -v
	sudo rm -fr persistence
    fi
fi
