---
version: '3'
services:
  traefik:
    image: traefik:1.7
    command: --web --docker --docker.domain=planet4.test --docker.watch
    networks:
      proxy:
        aliases:
          - ${APP_HOSTNAME:-www.planet4.test}
          - www.planet4.fnord
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.${APP_HOSTNAME:-www.planet4.test}"
      traefik.docker.network: "${COMPOSE_PROJECT_NAME}_proxy"
      traefik.enable: "true"

  redis:
    image: ${REDIS_IMAGE:-redis:4-stretch}
    networks:
      - local
    labels:
      traefik.enable: "false"

  db:
    build:
      context: defaultcontent
      dockerfile: ../db/Dockerfile
    env_file:
      - ./db.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
    labels:
      traefik.enable: "false"

  php-fpm:
    image: ${APP_IMAGE:-gcr.io/planet-4-151612/wordpress:main}
    depends_on:
      - db
      - redis
    networks:
      - local
      - db
      - proxy
    dns:
      - ${DNS_RESOLVER:-1.1.1.1}
    volumes:
      - ./persistence/app:/app/source:cached
      - excluded-theme:/app/source/public/wp-content/themes/planet4-master-theme/node_modules/
      - excluded-plugin:/app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/node_modules/
      - excluded:/app/source/node_modules/
      - ./secrets/wp-stateless-media-key.json:/app/secrets/wp-stateless-media-key.json:ro
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_HOSTNAME=${APP_HOSTNAME:-www.planet4.test}
      - APP_HOSTPATH=${APP_HOSTPATH:-}
      # - DELETE_EXISTING_FILES=false
      - GIT_REF=${GIT_REF:-main}
      - GIT_SOURCE=https://github.com/greenpeace/planet4-base
      - INSTALL_APM_AGENT=${INSTALL_APM_AGENT:-false}
      # - MERGE_REF=develop
      # - MERGE_SOURCE=https://github.com/greenpeace/planet4-flibble
      # - OVERWRITE_EXISTING_FILES=false
      - WP_FORCE_SSL_ADMIN=false
      - WP_REDIS_ENABLED=${WP_REDIS_ENABLED:-true}
      - WP_STATELESS_MEDIA_BUCKET=${APP_HOSTNAME:-www-planet4-test}
      - WP_STATELESS_MEDIA_ENABLED=${WP_STATELESS_MEDIA_ENABLED:-true}
      - WP_VERSION=5.6.2
      - CODECEPTION_SELENIUM_HOST=selenium
      - CODECEPTION_SELENIUM_PORT=4444
    env_file:
      - ./app.env
      - ./db.env
    labels:
      traefik.enable: "false"

  openresty:
    image: ${OPENRESTY_IMAGE:-gcr.io/planet-4-151612/openresty:main}
    depends_on:
      - php-fpm
      - traefik
      - redis
    networks:
      - local
      - proxy
    volumes:
      - ./persistence/app:/app/source:cached
      - excluded-theme:/app/source/public/wp-content/themes/planet4-master-theme/node_modules/
      - excluded-plugin:/app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/node_modules/
      - excluded:/app/source/node_modules/
    environment:
      - APP_ENV=${APP_ENV:-develop}
      - PAGESPEED_ENABLED=${PAGESPEED_ENABLED:-false}
      - APP_HOSTNAME=${APP_HOSTNAME:-www.planet4.test}
      - APP_HOSTPATH=${APP_HOSTPATH:-}
      - REDIS_FASTCGI_CACHE_ENABLED=true
      - PHP_ENABLED=true
    labels:
      - "traefik.backend=test"
      - "traefik.foo.frontend.rule=Host:${APP_HOSTNAME:-www.planet4.test}"
      - "traefik.bar.frontend.rule=Host:www.planet4.fnord"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_proxy"
      - "traefik.enable=true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
      - traefik
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
    env_file:
      - ./db.env
    volumes:
      - pma:/sessions
    networks:
      - db
      - proxy
    labels:
      traefik.backend: "pma"
      traefik.frontend.rule: "Host:pma.www.planet4.test"
      traefik.docker.network: "${COMPOSE_PROJECT_NAME}_proxy"
      traefik.enable: "true"

  elasticsearch:
    image: gcr.io/planet-4-151612/elasticsearch:${ELASTICSEARCH_BUILD_TAG:-latest}
    networks:
      - local
    environment:
      - discovery.type=single-node
    labels:
      traefik.enable: "false"

  elastichq:
    image: elastichq/elasticsearch-hq
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200
    networks:
      - local
    ports:
      - "5000:5000"

  selenium:
    image: selenium/standalone-chrome-debug:3
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - local
      - proxy
      - db
    labels:
      traefik.enable: "false"

  node:
    image: ${NODE_IMAGE:-node:16-alpine3.16}
    tty: true
    networks:
      - local
      - proxy
    dns:
      - ${DNS_RESOLVER:-1.1.1.1}
    volumes:
      - ./persistence/app:/app/source:cached
      - excluded-theme:/app/source/public/wp-content/themes/planet4-master-theme/node_modules/
      - excluded-plugin:/app/source/public/wp-content/plugins/planet4-plugin-gutenberg-blocks/node_modules/
      - excluded:/app/source/node_modules/
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=${PUPPETEER_SKIP_CHROMIUM_DOWNLOAD:-true}
      - PUPPETEER_SKIP_DOWNLOAD=${PUPPETEER_SKIP_DOWNLOAD:-true}

networks:
  local:
  db:
  proxy:
    driver: bridge

volumes:
  db:
  pma:
  excluded:
  excluded-theme:
  excluded-plugin:
