#!/usr/bin/env bash
set -e

if [[ $1 = "delete"  ]]
then
  docker-compose -f "${DOCKER_COMPOSE_FILE:-docker-compose.yml}" down -v
  set -x
  sudo rm -fr persistence
  set +x
  echo 0
fi

docker-compose -f "${DOCKER_COMPOSE_FILE:-docker-compose.yml}" down
