---
docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth
  working_directory: /home/circleci/app

version: 2

jobs:
  codeception:
    <<: *defaults
    environment:
      APP_IMAGE: gcr.io/planet-4-151612/planet4-base-app:main
      OPENRESTY_IMAGE: gcr.io/planet-4-151612/planet4-base-openresty:main
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
            - composer-v1-{{ .Branch }}-{{ .Revision }}
            - composer-v1-{{ .Branch }}
            - composer-v1
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make ci
      - save_cache:
          key: composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
          paths:
            - defaultcontent
      - run:
          name: Run acceptance tests
          command: make test
      - run:
          name: Generate artifacts
          command: make ci-extract-artifacts
          when: always
      - store_test_results:
          path: artifacts
      - store_artifacts:
          path: artifacts
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Codeception" notify-job-failure.sh

  localdev:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      APP_IMAGE: gcr.io/planet-4-151612/wordpress:main
      OPENRESTY_IMAGE: gcr.io/planet-4-151612/planet4-base-openresty:main
    steps:
      - checkout
      - run:
          name: Create local dev environment
          command: make dev
      - run:
          name: Basic checks
          command: ./scripts/status-report.sh

workflows:
  version: 2

  test:
    jobs:
      - localdev
      - codeception:
          context: org-global

  cron-test:
    jobs:
      - localdev
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
