---
version: 2.1

docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth
  working_directory: /home/circleci/app

jobs:
  codeception:
    <<: *defaults
    environment:
      APP_IMAGE: gcr.io/planet-4-151612/planet4-base-app:main
      OPENRESTY_IMAGE: gcr.io/planet-4-151612/planet4-base-openresty:main
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
            - composer-v1-{{ .Branch }}-{{ .Revision }}
            - composer-v1-{{ .Branch }}
            - composer-v1
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make ci
      - save_cache:
          key: composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
          paths:
            - defaultcontent
      - run:
          name: Run acceptance tests
          command: make test
      - run:
          name: Generate artifacts
          command: make ci-extract-artifacts
          when: always
      - store_test_results:
          path: artifacts
      - store_artifacts:
          path: artifacts
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Codeception" notify-job-failure.sh

  localdev:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      APP_IMAGE: gcr.io/planet-4-151612/wordpress:main
      OPENRESTY_IMAGE: gcr.io/planet-4-151612/planet4-base-openresty:main
    steps:
      - checkout
      - run:
          name: Create local dev environment
          command: make dev
      - run:
          name: Basic checks
          command: ./scripts/status-report.sh
      - run:
          name: Create release from install
          command: |
              mkdir -p /tmp/workspace/build
              export DEVRELEASE_VERSION="$(date +'%Y%m%d')"
              # <sudo> to bypass permissions issues with wflogs files
              RELEASE=$(sudo -E make create-dev-export)
              echo "${RELEASE}" > /tmp/workspace/build/release.txt
              mv "${RELEASE}" /tmp/workspace/build/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build/*

  dev-from-release:
    machine:
      image: ubuntu-2004:202101-01
    environment:
      APP_IMAGE: gcr.io/planet-4-151612/wordpress:main
      OPENRESTY_IMAGE: gcr.io/planet-4-151612/planet4-base-openresty:main
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Create local environment from release
          command: |
              cp /tmp/workspace/build/* .
              LOCAL_DEVRELEASE=$(cat /tmp/workspace/build/release.txt) make dev-from-release
      - run:
          name: Basic checks
          command: ./scripts/status-report.sh

  publish-release:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet-4-151612
      BUCKET_NAME: planet4-default-content
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run: activate-gcloud-account.sh
      - run:
          name: Push dev release to cloud storage
          command: |
              RELEASE=$(cat /tmp/workspace/build/release.txt)
              LATEST="planet4-persistence-latest.gz"
              gsutil cp -a public-read /tmp/workspace/build/${RELEASE} gs://${BUCKET_NAME}
              mv /tmp/workspace/build/${RELEASE} /tmp/workspace/build/${LATEST}
              gsutil cp -a public-read /tmp/workspace/build/${LATEST} gs://${BUCKET_NAME}

  lint:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Lint
          command: |
            make lint
            make lint-commit

workflows:
  test:
    jobs:
      - localdev
      - dev-from-release:
          requires:
            - localdev
      - codeception:
          context: org-global
      - lint

  nightly-test-and-release:
    jobs:
      - localdev
      - dev-from-release:
          requires:
            - localdev
      - codeception:
          context: org-global
      - publish-release:
          context: org-global
          requires:
            - localdev
            - dev-from-release
            - codeception
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
